class ClassSpec {
  final List<String> classes = <String>[
    "Paladin",
    "Death Knight",
    "Demon Hunter",
    "Druid",
    "Hunter",
    "Mage",
    "Monk",
    "Priest",
    "Rogue",
    "Shaman",
    "Warlock",
    "Warrior",
  ];

  final Map<String, List<String>> spec = {
    "Paladin": ["Holy", "Retribution", "Protection"],
    "Death Knight": ["Blood", "Unholy", "Frost"],
    "Demon Hunter": ["Havoc", "Vengeance"],
    "Druid": ["Balance", "Restoration", "Feral", "Guardian"],
    "Hunter": ["Beast Master", "Survival", "Marksmanship"],
    "Mage": ["Frost", "Fire", "Arcane"],
    "Monk": ["Windwalker", "Mistweaver", "Brewmaster"],
    "Priest": ["Discipline", "Holy", "Shadow"],
    "Rogue": ["Subtlety", "Assassination", "Outlaw"],
    "Shaman": ["Elemental", "Restoration", "Enhancement"],
    "Warlock": ["Affliction", "Destruction", "Demonology"],
    "Warrior": ["Arms", "Fury", "Protection"],
  };
  final Map<String, List<String>> roles = {
    "DPS": [
      "Retribution",
      "Unholy",
      "Frost",
      "Havoc",
      "Balance",
      "Feral",
      "Beast Master",
      "Survival",
      "Marksmanship",
      "Fire",
      "Arcane",
      "Windwalker",
      "Shadow",
      "Subtlety",
      "Assassination",
      "Outlaw",
      "Elemental",
      "Enhancement",
      "Affliction",
      "Destruction",
      "Demonology",
      "Arms",
      "Fury",
    ],
    "Healer": ["Holy", "Restoration", "Mistweaver", "Discipline"],
    "Tank": ["Protection", "Blood", "Vengeance", "Brewmaster"],
  };
}
